global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs: [{ targets: ['prometheus:9090'] }]

  - job_name: 'grafana'
    static_configs: [{ targets: ['grafana:3000'] }]

  - job_name: 'node'
    static_configs: [{ targets: ['172.17.0.1:9100'] }]

  - job_name: 'cadvisor'
    static_configs: [{ targets: ['cadvisor:8080'] }]

  - job_name: 'postgres'
    static_configs: [{ targets: ['postgres-exporter:9187'] }]

  - job_name: 'redis'
    static_configs: [{ targets: ['redis-exporter:9121'] }]

  - job_name: 'n8n'
    metrics_path: /metrics
    file_sd_configs:
      - files:
        - /etc/prometheus/targets/n8n.json
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  # ---- blackbox (HTTP доступность n8n) ----
  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://n8n-n8n-main-1:5678
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: 'blackbox_http_public'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://n8n.amaxbox.me
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
